name: I. Am. Carrico. Recipies
author: https://iamcarrico.com/about/
lsi: false
debug: false

# Temporarily in here while I debug stuff.
minify_html: false

permalink: /recipies/:title/
url: https://recipies.iamcarrico.com
paginate: 4
paginate_path: "recipies/page/:num/"
timezone: America/Chicago
future: true

category_dir: topics
exclude:
  - CONTRIBUTING.md
  - README.md
  - config.rb
  - package.json
  - gulpfile.js
  - node_modules
  - Gemfile
  - Gemfile.lock
  - css
  - LICENSE

markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]

development: false

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

assets:
  dirname: assets
  sources:
    - js
    - css
    - img
    - bower_components
  js_compressor: 'uglifier'
  css_compressor: 'yui'
  cache: true
